betonavi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse


urlpatterns = [
    url(r'', include('webapp.urls')),
    url(r'^mobile/api/', include('mobile.urls')),
    url(r'^translatex/', include('translatex.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^tinymce/', include('tinymce.urls')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow:", content_type="text/plain"), name="robots_file"),

] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mobile/urls.py
from django.conf.urls import url
import views


urlpatterns = (

  # Get shop list
  url(r'^home$', views.home),
  url(r'^barcode_search$', views.barcode_search),
  url(r'^search$', views.search),

  url(r'^favorite$', views.favorite),
  url(r'^device$', views.favorite),


  url(r'^favorite$', views.favorite),
)

translatex/urls.py
from django.conf.urls import url
import views


urlpatterns = (

  # Get shop list
  url(r'^$', views.index, name="translatex_list"),
  url(r'^guide$', views.guide),
  url(r'^billings$', views.billing),
  url(r'^members$', views.members),
  url(r'^all_products$', views.all_products),
  url(r'^sp/(?P<id>[0-9]+)$', views.detail, name="translatex_detail"),

  # online status api
  url(r'^api/online_status$', views.online_status),
)

mobile/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.files import File
import urllib
import json
from django.conf import settings
from webapp.models import AmazonProduct


class Device(models.Model):
    device_uuid = models.CharField(max_length=200, blank=True, null=True)

    device_manufacturer = models.CharField(max_length=200, blank=True, null=True)
    device_name = models.CharField(max_length=200, blank=True, null=True)
    device_model = models.CharField(max_length=200, blank=True, null=True)
    device_locale = models.CharField(max_length=200, blank=True, null=True)
    device_country = models.CharField(max_length=200, blank=True, null=True)
    user_agent = models.CharField(max_length=2000, blank=True, null=True)
    device_system_name = models.CharField(max_length=200, blank=True, null=True)
    device_id = models.CharField(max_length=200, blank=True, null=True)
    device_version = models.CharField(max_length=200, blank=True, null=True)
    bundle_id = models.CharField(max_length=200, blank=True, null=True)
    build_number = models.CharField(max_length=200, blank=True, null=True)
    app_version = models.CharField(max_length=200, blank=True, null=True)
    app_version_readable = models.CharField(max_length=200, blank=True, null=True)


    notification = models.BooleanField(default=True)
    fcm_token = models.CharField(max_length=512, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Favorite(models.Model):
    device = models.ForeignKey(Device, blank=True, null=True)
    amazon_product = models.ForeignKey(AmazonProduct, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

translatex/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.files import File
import urllib
import json
from django.conf import settings
from webapp.models import *
from django.contrib.auth.models import User
from .constants import *
from datetime import datetime
import uuid
from django.db.models import Sum, Avg
from django.template.defaultfilters import truncatechars  # or truncatewords


class Translator(models.Model):
    user = models.ForeignKey(User, blank=True, null=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    fullname = models.CharField(max_length=64, blank=True, null=True)

    bank_account_info = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def translated_num_in_month(self):
        now = datetime.now()

        return ProductTranslation.objects.filter(
            assignee=self,
            status=4,
            # closed_at__year=now.year,
            # closed_at__month=now.month,
            is_paid=False
        ).count()

    def rating_avg_in_month(self):
        now = datetime.now()
        return ProductTranslation.objects.filter(
            assignee=self,
            status=4,
            # closed_at__year=now.year,
            # closed_at__month=now.month,
            is_paid=False
        ).aggregate(Avg('rating'))['rating__avg']

    def charge_amount_in_month(self):
        now = datetime.now()
        return ProductTranslation.objects.filter(
            assignee=self,
            status=4,
            # closed_at__year=now.year,
            # closed_at__month=now.month,
            is_paid=False
        ).aggregate(Sum('charge_amount'))['charge_amount__sum']

    def __unicode__(self):
        return u'%s' % self.fullname


class ProductTranslation(models.Model):
    amazon_product = models.ForeignKey(AmazonProduct, blank=True, null=True)
    product = models.ForeignKey(Product, blank=True, null=True, on_delete=models.SET_NULL)
    assignee = models.ForeignKey(Translator, blank=True, null=True, verbose_name='Người dịch', on_delete=models.SET_NULL)
    reviewer1 = models.ForeignKey(User, blank=True, null=True, related_name='reviewer1', on_delete=models.SET_NULL)
    reviewer2 = models.ForeignKey(User, blank=True, null=True, related_name='reviewer2', on_delete=models.SET_NULL)

    # japanese fields
    jp_name = models.CharField(max_length=1024, blank=True, null=True)
    jp_introduction = models.TextField(blank=True, null=True)
    jp_description = models.TextField(blank=True, null=True)
    jp_content = models.TextField(null=True, blank=True)

    # vietnamese fields
    vn_name = models.CharField(max_length=1024, blank=True, null=True, verbose_name='Tên sản phẩm')
    vn_introduction = models.TextField(blank=True, null=True, verbose_name='Giới thiệu')
    vn_description = models.TextField(blank=True, null=True, verbose_name='Mô tả')
    vn_usage = models.TextField(null=True, blank=True, verbose_name='Cách sử dụng')
    vn_notice = models.TextField(null=True, blank=True, verbose_name='Chú ý')
    vn_content = models.TextField(null=True, blank=True)

    # reference url
    reference_url1 = models.CharField(max_length=512, null=True, blank=True, verbose_name='Link tham khảo 1')
    reference_url2 = models.CharField(max_length=512, null=True, blank=True, verbose_name='Link tham khảo 2')
    reference_url3 = models.CharField(max_length=512, null=True, blank=True, verbose_name='Link tham khảo 3')
    translated_time = models.IntegerField(default=0, null=True, blank=True, verbose_name='Thời gian dịch')
    translated_rate = models.IntegerField(default=0, null=True, blank=True, verbose_name='phần trăm dịch')

    similar_eans = models.TextField(null=True, blank=True)

    # Translated words count
    word_count = models.IntegerField(default=0, null=True, blank=True)
    charge_amount = models.IntegerField(default=0, null=True, blank=True)

    old_vn_name = models.CharField(max_length=1024, blank=True, null=True, verbose_name='Tên sản phẩm')
    old_word_count = models.IntegerField(default=0, null=True, blank=True)

    is_paid = models.BooleanField(default=False)

    is_done = models.BooleanField(default=False) # copy back to product master

    status = models.IntegerField(
        default=0,
        choices=TICKET_STATUS_OPTIONS,
        null=True,
        blank=True, verbose_name='Trạng thái')

    rating = models.IntegerField(
        default=0,
        choices=TICKET_REVIEW_OPTIONS,
        null=True,
        blank=True, verbose_name='Đánh giá')

    closed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def similar_product_count(self):
        return len(self.similar_eans.split(',')) if self.similar_eans else 0

    @property
    def similar_products(self):
        if self.similar_eans:
            return ProductTranslation.objects.filter(
                amazon_product__ean__in=self.similar_eans.split(','))
        return None

    @property
    def short_title(self):
        return truncatechars(self.amazon_product.title, 100) if self.amazon_product else ''

    @property
    def short_vn_name(self):
        return truncatechars(self.vn_name, 100)

    @property
    def estimate(self):
        charge_amount = 0

        translatedRate = self.translated_rate or 0

        if self.status > 1:
            # base amount
            charge_amount = 6000

            # translation rate
            charge_amount += max(translatedRate - 50, 0) * 100

            # word count (length of content)
            if self.word_count < 200:
                charge_amount += -2000
            elif 400 < self.word_count < 700:
                charge_amount += 2000
            elif self.word_count >= 700:
                charge_amount += 5000

            # rating
            charge_amount += 3000

        return charge_amount

    def save(self, *args, **kwargs):
        # couting words
        name_len = len(self.vn_name.split()) if self.vn_name else 0
        introduction_len = len(self.vn_introduction.split()) if self.vn_introduction else 0
        description_len = len(self.vn_description.split()) if self.vn_description else 0
        usage_len = len(self.vn_usage.split()) if self.vn_usage else 0
        notice_len = len(self.vn_notice.split()) if self.vn_notice else 0
        self.word_count = name_len + introduction_len + description_len + usage_len + notice_len
        super(ProductTranslation, self).save(*args, **kwargs)


class TranslationComment(models.Model):
    product = models.ForeignKey(ProductTranslation, blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Billing(models.Model):
    translator = models.ForeignKey(Translator, blank=True, null=True)
    year = models.IntegerField(choices=((2017, 2017,), (2018, 2018, ), ),blank=True, null=True)
    month = models.IntegerField(blank=True, null=True)
    charge_amount = models.IntegerField(blank=True, null=True)
    bonus = models.IntegerField(default=0, blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    paid_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Notification(models.Model):
    product = models.ForeignKey(ProductTranslation, blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True)
    message = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

translatex/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.conf import settings
from .constants import TICKET_STATUS_OPTIONS, TICKET_REVIEW_OPTIONS, TRANSLATOR_STATUS_OPTIONS
from .models import *
from django.contrib.auth.models import User


class TicketStatusForm(forms.Form):
    status = forms.ChoiceField(
        required=True,
        label='Trạng thái',
        choices=TRANSLATOR_STATUS_OPTIONS,
        widget=forms.Select(attrs={'class': 'form-control'}))


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ProductTranslation
        fields = ['assignee', 'status', 'rating', 'charge_amount' ]

class ContentForm(forms.ModelForm):
    class Meta:
        model = ProductTranslation
        fields = ['vn_name', 'vn_introduction', 'vn_description', 'vn_usage', 'vn_notice' ]

class EditTicketForm(forms.ModelForm):
    class Meta:
        model = ProductTranslation
        fields = ['reference_url1',
            'translated_time',
            'reference_url2',
            'translated_rate',
            'reference_url3',
         ]


class TranslationCommentForm(forms.Form):
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 6,
            'cols': 80
            }
    ))


class TranslatorForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all(),
                                  widget=forms.TextInput)
    class Meta:
        model = Translator
        fields = ['user', 'fullname', 'bank_account_info', ]

translatex/templates/translatex/mobile/base.html
<!doctype html>
<html lang="vi">
    <head>
       <meta charset="utf-8">
       <title>PTP - Betonavi Product Translation Platform</title>
       <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load staticfiles %}

        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{% static 'translatex/stylesheets/animate.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'translatex/stylesheets/common.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'translatex/stylesheets/mobile.css' %}">
        <link rel="stylesheet" href="{% static 'translatex/font-awesome/css/font-awesome.min.css' %}">

        {% block css %}
        {% endblock %}

    </head>
    <body >
        <div id="header">
          <a class="logo" href="/translatex">PTP</a>

          <p class="link">
            <a class="{% if tab == 1 %} active {% endif %}" href="/translatex/">Danh sách</a>
            <!-- <a class="{% if tab == 2 %} active {% endif %}" href="/translatex/guide">Hướng dẫn</a> -->
            <a class="{% if tab == 3 %} active {% endif %}" href="/translatex/billings">Thanh Toán</a>
          </p>

          <div class="user-tools">
            <span id="bell" class="bell">
              <i class="fa fa-bell" aria-hidden="true"></i>
              <span class="dot"></span>
            </span>

            Hi, {{ request.user.username }}

            &nbsp;

            <a href="https://betonavi.com/accounts/logout/">logout</a>
          </div>
        </div>


        {% block content %}
        {% endblock %}

        <div id="notification">
          <span class="title">NOTIFICATION CENTER</span>
          <ul>
            {% for item in request.notifications %}
            <li>
              <a href="/translatex/sp/{{item.product.id}}"><span>{{ item.message }}. </span></a>
              <time class="timeago" datetime="{{item.created_at|date:"c"}}">{{item.created_at}}</time>
            </li>
            {% endfor %}
            <li>
              <span>Chào mừng bạn đến với Platform dịch sản phẩm của Betonavi. </span>
            </li>

          </ul>
        </div>

        <script type="text/javascript" src="{% static 'translatex/bower_components/jquery/dist/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'translatex/bower_components/jquery-timeago/jquery.timeago.js' %}"></script>
        <script type="text/javascript" src="{% static 'translatex/js/common.js' %}"></script>

        {% block js %}
        {% endblock %}

    </body>
</html>

translatex/templates/translatex/mobile/billing.html
{% extends "./base.html" %}

{% load staticfiles %}
{% load humanize %}

{% block content %}


    <div class="wrapper">

      <h1>Billing</h1>

      <hr>

      <h3>Tháng {{ month }}, {{ year}}</h3>

      <table id="ticket_list">
        <thead>
          <tr>
            <td>Username</td>
            <td>F/T</td>
            <td>Avg Star</td>
            <td>Charge</td>
          </tr>
        </thead>
        <tbody>
          {% for item in translators %}
          <tr>
            <td>
              {% if request.user.is_staff %}
                <a href="{% url 'translatex_list' %}?u={{item.user.username}}">{{ item.user.username }}</a>
              {% else %}
                {{ item.user.username }}
              {% endif %}
            </td>
            <td>
              {{ item.translated_num_in_month }} / {{ item.producttranslation_set.all|length }}
            </td>
            <td>{{ item.rating_avg_in_month|default_if_none:"-" }} / 5</td>
            <td> <span class="price">{{ item.charge_amount_in_month|default_if_none:"-"|intcomma }}</span></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>


    </div>

{% endblock %}

translatex/templates/translatex/mobile/detail.html
{% extends "./base.html" %}

{% load staticfiles %}
{% load humanize %}

{% block content %}
<script>
function goBack() {
    window.history.back();
}
</script>

<div id="mobile_detail_page">
  <p>
    <a href="javascript:void(0)" onclick="goBack()">Go Back</a>
  </p>
  {% if request.user.is_staff and product.similar_product_count > 0 %}
    <h3>Similar products</h3>
    <div id="similars">
      <div class="scroller">
        <div class="item current">
          <div class="image"
              style="background-image: url({{ product.amazon_product.medium_image_url }})"></div>
          <div class="name">{{ product.amazon_product.title }}</div>
          <div class="status status-{{ product.status}}">{{ product.get_status_display }}</div>
          {% if product.assignee %}
            <div class="assignee">{{ product.assignee.user.username }}</div>
          {% endif %}
        </div>

        {% for item in product.similar_products %}
          <a target="_blank" href="/translatex/sp/{{item.id}}">
            <div class="item">
              <div class="image"
                  style="background-image: url({{ item.amazon_product.medium_image_url }})"></div>
              <div class="name">{{ item.amazon_product.title }}</div>
              <div class="status status-{{item.status}}">{{ item.get_status_display }}</div>

              {% if item.assignee %}
                <div class="assignee">{{ item.assignee.user.username }}</div>
              {% endif %}
            </div>
          </a>
        {% endfor %}
      </div>
    </div>
  {% endif %}



  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}


  <h3>#{{product.id}} - {{ product.amazon_product.title }}</h3>

  <div id="control">

    {% if not request.user.is_staff %}
    <div class="translator">
      {% if product.status is None or product.status < 3 or product.status == 10 %}
      <form action="/translatex/sp/{{ product.id }}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="type" value="status" >
        {{ status_form }}
        <button class="btn" type="submit">Lưu lại</button>
      </form>
      {% else %}
        <label for="id_status">Trạng thái:</label>
        <span class="status status-{{product.status}}">
          {{ product.get_status_display }}
        </span>
      {% endif %}
    </div>
    {% else %}
    <div class="reviewer">
      <form action="/translatex/sp/{{ product.id }}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="type" value="review" >
        {{ review_form.as_p }}

        <p class="estimate">
          <span>Ước lượng chi phí: </span>
          <span class="price">{{ product.estimate }} đ</span>
        </p>

        <button class="btn" type="submit">Lưu lại</button>
      </form>
    </div>
    {% endif %}

  </div>

  <hr>

  <div id="reference">
    <form  action="/translatex/sp/{{ product.id }}" method="POST">
      <input type="hidden" name="type" value="edit" >
      {% csrf_token %}
      {{ edit_form.as_p }}
    </form>
  </div>

  <hr>
  <div class="links">
    <a target="_blank" href="https://www.amazon.co.jp/dp/{{product.amazon_product.asin}}">
      link amazon <i class="fa fa-external-link" aria-hidden="true"></i>
    </a>

    {% if product.amazon_product and product.amazon_product.product %}
    <a target="_blank" href="https://betonavi.com/dp/{{product.amazon_product.asin}}">
      link betonavi <i class="fa fa-external-link" aria-hidden="true"></i>
    </a>
    {% endif %}
  </div>


  <div class="editor" id="editor">
    <div class="row preview">
      <h1>Preview</h1>
      <div class="pv_label">Tên sản phẩm</div>
      <h3 id="pv_vn_name">
        {{ product.vn_name|default_if_none:'-' }}
      </h3>

      <div class="pv_label">Giới thiệu</div>
      <div id="pv_vn_introduction" class="">
        {{ md_introduction|safe }}
      </div>

      <div class="pv_label">Mô tả</div>
      <div id="pv_vn_description" class="">
        {{ md_description|safe }}
      </div>

      <div class="pv_label">Cách sử dụng</div>
      <div id="pv_vn_usage" class="">
        {{ md_usage|safe }}
      </div>

      <div class="pv_label">Chú ý</div>
      <div id="pv_vn_notice" class="">
        {{ md_notice|safe }}
      </div>
    </div>
  </div>


  <div id="comment">

    <h3>Comments</h3>

    <form  action="/translatex/sp/{{ product.id }}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="type" value="comment" >
      <textarea name="message" id="id_message" required=""  class="form-control"></textarea>
      <br>
      <input  class="btn" type="submit" value="Send">
    </form>

    {% for item in comments %}
      <div class="item">
        <div class="info">
            <span class="user">{{item.user}}</span>
            <span class="time">{{item.created_at}}</span>
        </div>
        <p>{{ item.text }}</p>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}


{% block js %}
<script type="text/javascript" src="{% static 'translatex/bower_components/showdown/dist/showdown.min.js' %}"></script>
<script type="text/javascript" src="{% static 'translatex/js/detail.js' %}"></script>
{% endblock %}

translatex/templates/translatex/mobile/index.html
{% extends "./base.html" %}

{% load staticfiles %}
{% load humanize %}

{% block content %}

  <div class="wrapper">
    <div class="filter">
      <span>Status</span>
      <select id="statusFilter" name="">
        <option value="{% url 'translatex_list' %}?u={{request.GET.u}}">-----------</option>
        {% for item in status %}
          <option
            {% if filtered_status == item.0 %} selected="selected" {% endif %}
            value="{% url 'translatex_list' %}?status={{item.0}}&u={{request.GET.u}}">{{ item.1 }}</option>
        {% endfor %}
      </select>

      <br>

      {% if request.user.is_staff %}
      <span>Translator</span>
      <select id="assigneeFilter" name="">
        <option value="{% url 'translatex_list' %}?status={{request.GET.status}}">-----------</option>
        {% for item in translators %}
          <option
            {% if request.GET.u == item.user.username %} selected="selected" {% endif %}
            value="{% url 'translatex_list' %}?u={{item.user.username}}&status={{request.GET.status}}" >{{ item.fullname }}</option>
        {% endfor %}
      </select>
      {% endif %}

      <a id="clearFilter" href="/translatex">Reset</a>
    </div>

    <div class="product_list">
      {% for item in products %}
        <a href="/translatex/sp/{{ item.id }}">
          <div class="item">
            <div class="thumbnail"
                style="background-image: url({{ item.amazon_product.medium_image_url }})"></div>

            <div class="name">
              {% if item.vn_name|length > 10 %}
                {{ item.vn_name|default_if_none:"-" }}
              {% else %}
                {{ item.amazon_product.title|truncatechars:20 }}
              {% endif %}
            </div>

            <div class="flex">
              <div class="col">
                <div class="">
                  {{ item.assignee }}
                </div>
                <div class="price">{{ item.charge_amount|intcomma }}</div>
              </div>
              <div class="col">
                <div class="status status-{{item.status}}">
                  {{ item.get_status_display|default_if_none:"-" }}
                </div>

                <div class="">
                  {% if item.rating is not None %}
                    {% with ''|center:item.rating as range %}
                      {% for i in range %}
                        <i class="fa fa-star" aria-hidden="true"></i>
                      {% endfor %}
                    {% endwith %}
                  {% endif %}
                </div>
              </div>
            </div>








          </div>
        </a>
      {% endfor %}
    </div>



    <div class="pagination">
      <div class="step-links">
          {% if products.has_previous %}
              <a class="link" href="?page={{ products.previous_page_number }}&u={{request.GET.u}}&status={{request.GET.status}}">&laquo; Trang Trước</a>
          {% endif %}

          <span class="current">
              {{ products.number }} / {{ products.paginator.num_pages }}
          </span>

          {% if products.has_next %}
              <a class="link" href="?page={{ products.next_page_number }}&u={{request.GET.u}}&status={{request.GET.status}}">Trang Tiếp &raquo;</a>
          {% endif %}
      </div>
  </div>

  </div>

{% endblock %}